lib/compare_linker/github_link_finder.rb
spec/fixtures/not_found.json
spec/lib/compare_linker/github_link_finder_spec.rb

recover of `unexpected token at 'This rubygem could not be found.' (JSON::ParserError)`.

Rescue JSON::ParserError

---

spec/lib/compare_linker/github_link_finder_spec.rb

Avoid `CompareLinker::GithubLinkFinder#redirect_url` to access to GitHub in spec

Fix spec failures

---

lib/compare_linker/github_link_finder.rb

http://github.com/opscode/chef/ returns the following header.
```
HTTP/1.1 302 Found
Connection: close
Pragma: no-cache
cache-control: no-cache
Location: /TXQcK/opscode/chef/
```
I believe Location fieald must be absoluteURI for RFC2396. However I add the workaround.

Add workaround which Location Header isnot absoluteURI

---

lib/compare_linker/github_link_finder.rb
spec/lib/compare_linker/github_link_finder_spec.rb

やっぱり https://rubygems.org/api/v1/gems/chef.json にはこれが必要だ。

Revert CompareLinker::GithubLinkFinder#redirect_url

---

lib/compare_linker/github_link_finder.rb

Hi,
Thanks for circleci-bundle-update-pr & compare_linker :)
Today,
`"coffee-script-source (http://jashkenas.github.com/coffee-script/): 1.9.1 => 1.9.1.1"`
causes this error:
```
* [new branch]      bundle-update-20150413 -> bundle-update-20150413
/home/ubuntu/esa/vendor/bundle/ruby/2.2.0/gems/compare_linker-1.1.7/lib/compare_linker/github_link_finder.rb:52:in `redirect_url': item not found (RuntimeError)
from /home/ubuntu/esa/vendor/bundle/ruby/2.2.0/gems/compare_linker-1.1.7/lib/compare_linker/github_link_finder.rb:50:in `redirect_url'
from /home/ubuntu/esa/vendor/bundle/ruby/2.2.0/gems/compare_linker-1.1.7/lib/compare_linker/github_link_finder.rb:26:in `find'
from /home/ubuntu/esa/vendor/bundle/ruby/2.2.0/gems/compare_linker-1.1.7/lib/compare_linker.rb:34:in `block in …
```

Fix item not found

---

lib/compare_linker/github_link_finder.rb
spec/fixtures/not_found.json
spec/lib/compare_linker/github_link_finder_spec.rb

Improve #13 
`HTTPClient::BadResponseError` surely occurs before `JSON::ParserError`.

Fix error on rails assets org

---

lib/compare_linker/github_link_finder.rb

```
HTTPClient::BadResponseError: unexpected response: #<HTTP::Message::Headers:0x007faa9f6f9518 @http_version="1.1", @body_size=0, @chunked=false, @request_method="GET", @request_uri=#<Addressable::URI:0x3fd54fb7d068 URI:https://rubygems.org/api/v1/gems/rails-assets-momentjs.json>, @request_query=nil, @request_absolute_uri=nil, @status_code=404, @reason_phrase="Not Found", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Server", "nginx"], ["Date", "Mon, 13 Apr 2015 05:43:49 GMT"], ["Content-Type", "application/json; charset=utf-8"], ["Transfer-Encoding", "chunked"], ["Connection", "keep-alive"], ["Status", "404 Not Found"], ["X-Frame-Options", "SAMEORIGIN"], ["X-XSS-Protection", "1; mode=block"], …
```

Fix not found error for gems on rails-assets.org

---

data/rubygems.yml
lib/compare_linker.rb
lib/compare_linker/formatter/base.rb
lib/compare_linker/formatter/markdown.rb
lib/compare_linker/formatter/text.rb
lib/compare_linker/gem_dictionary.rb
lib/compare_linker/github_link_finder.rb
lib/compare_linker/github_tag_finder.rb
spec/lib/compare_linker/gem_dictionary_spec.rb
spec/lib/compare_linker/github_link_finder_spec.rb

* Rescue gems that doesn't have GitHub URL
* e.g. https://rubygems.org/gems/capistrano
* Rescue gems that has many tags
* e.g. https://github.com/newrelic/rpm/tags
* Rescue gems that has tag names `<gem_name>-<version>`
* https://github.com/djberg96/sys-proctable/tags

Rescue missing GitHub compare links

---

README.md
lib/compare_linker.rb

I added GitHub Enterprise support.
Because github enterprise has different access control, add enterprise_octokit.
It can also be used by setting ENTERPRISE_OCTOKIT_ACCESS_TOKEN and ENTERPRISE_OCTOKIT_HOST in environment variables.
- I confirmed the operation with Github Enterprise I have contracted
- I confirmed that the original processing is not affected by normal Github

Add GitHub Enterprise support

---

lib/compare_linker/formatter/base.rb

I got following error using https://github.com/walf443/compare_linker/tree/detect_argument_error branch
```
[test_compare_linker_fix 9c9d4a9] $ bundle update && bundle update --ruby
1 file changed, 17 insertions(+), 17 deletions(-)
Traceback (most recent call last):
10: from /usr/local/bundle/bin/circleci-bundle-update-pr:23:in `<main>'
9: from /usr/local/bundle/bin/circleci-bundle-update-pr:23:in `load'
8: from /usr/local/bundle/gems/circleci-bundle-update-pr-1.11.1/bin/circleci-bundle-update-pr:13:in `<top (required)>'
7: from /usr/local/bundle/gems/circleci-bundle-update-pr-1.11.1/lib/circleci/bundle/update/pr.rb:23:in `create_if_needed'
6: from /usr/local/bundle/gems/circleci-bundle-update-pr-1.11.1/lib/circleci/bundle/update/pr.rb:63:in `update_pull_request_body'
5: from …
```

handle downgrade? error

---

compare_linker.gemspec
lib/compare_linker.rb

I want to use `compare_linker` from outside GitHub (e.g. GitLab)
So I want to use following from my code.
https://github.com/masutaka/compare_linker/blob/v1.4.2/lib/compare_linker.rb#L29-L60
```ruby
gitlab = Gitlab.client
old_lockfile = gitlab.file_contents("my/project", "Gemfile.lock", "OLD_SHA1")
new_lockfile = gitlab.file_contents("my/project", "Gemfile.lock", "NEW_SHA1")
compare_linker = CompareLinker.new("dummy", "dummy")
compare_linker.make_compare_links_from_lockfiles(Bundler::LockfileParser.new(old_lockfile), Bundler::LockfileParser.new(new_lockfile))
```

Refactor: extract to make_compare_links_from_lockfiles

---

lib/compare_linker/lockfile_fetcher.rb

I use [circleci-bundle-update-pr](https://github.com/masutaka/circleci-bundle-update-pr) on GitHub Actions
Suddenly the following error occurs and the body of the PullRequest is not generated 😢 
Error log
```bash
+ circleci-bundle-update-pr CircleCI-bundle-updater xxxxxx@example.com --assignees sue445 main
To use multipart middleware with Faraday v2.0+, install `faraday-multipart` gem; note: this is used by the ManageGHES client for uploading licenses
(snip)
/opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/gems/3.2.0/gems/compare_linker-1.4.4/lib/compare_linker/lockfile_fetcher.rb:18:in `fetch': uninitialized constant CompareLinker::LockfileFetcher::Base64 (NameError)
bundle-update-20240615040328 is created
Base64.decode64(
^^^^^^
from …
```

Fixed `uninitialized constant CompareLinker::LockfileFetcher::Base64 (NameError)`

---

README.md

Recently, the repositories I am involved with all have the default branch named `main`, so I would like to align the names accordingly.

Rename branch from `master` to `main`

---

compare_linker.gemspec

🔗 https://github.com/masutaka/circleci-bundle-update-pr/pull/173#issuecomment-2205974289
> https://app.circleci.com/pipelines/github/masutaka/circleci-bundle-update-pr/414/workflows/acffdcc2-67f7-4e0d-bda8-fc691e47d28f/jobs/1803
>
>> /home/circleci/repo/vendor/bundle/ruby/3.3.0/gems/compare_linker-1.4.5/lib/compare_linker/lockfile_fetcher.rb:2: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of compare_linker-1.4.5 to add base64 into its gemspec.
>
> あとで直すか。
It's related to https://github.com/masutaka/compare_linker/pull/44

Fix base64 warning

---

.github/workflows/test.yml
compare_linker.gemspec

The test failure occured in #49 test:
🔗 https://github.com/masutaka/compare_linker/actions/runs/10349442581/job/28644229198
> An error occurred while loading ./spec/lib/compare_linker/formatter/markdown_spec.rb.
> Failure/Error: require 'factory_bot'
>
> NameError:
>   uninitialized constant #<Class:ActiveSupport::Delegation>::Inflector
> \# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.0/lib/active_support/delegation.rb:47:in \`generate'
> \# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.0/lib/active_support/core_ext/module/delegation.rb:161:in \`delegate'
> \# ./vendor/bundle/ruby/3.3.0/gems/factory_bot-6.4.6/lib/factory_bot/definition_hierarchy.rb:3:in \`<class:DefinitionHierarchy>'
> \# ./vendor/bundle/ruby/3.3.0/gems/factory_bot-6.4.6/lib/factory_bot/definition_hierarchy.rb:2: …

Add workaround to factory_bot and activesupport dependencies

---

.github/workflows/schedule.yml
.github/workflows/test.yml

Since it is always slow to run CodeQL tests, optimize the timing of execution using [route06/actions](https://github.com/route06/actions).
* Run CodeQL only when necessary
* Run CodeQL every Friday
* Since default CodeQL is also executed on a scheduled basis

Add CodeQL jobs to GitHub Actions workflow

---

compare_linker.gemspec

:link: https://github.com/masutaka/circleci-bundle-update-pr/pull/189#issuecomment-2386242110
> /home/circleci/repo/vendor/bundle/ruby/3.3.0/gems/compare_linker-1.4.7/lib/compare_linker.rb:2: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
> You can add ostruct to your Gemfile or gemspec to silence this warning.

Add dependency with ostruct

---

compare_linker.gemspec

This PR removes the workaround added by https://github.com/masutaka/compare_linker/pull/50 .

Remove workaround to factory_bot and activesupport dependencies

---

lib/compare_linker/github_link_finder.rb
spec/lib/compare_linker/github_link_finder_spec.rb

It resolves the CI errors of PR https://github.com/masutaka/compare_linker/pull/66.

Fix uninitialized constant error in ruby-3.2 and less for PR #66

---

lib/compare_linker/github_link_finder.rb
spec/lib/compare_linker/github_link_finder_spec.rb

Hello!
I have been using the [compare_linker gem](https://gitlab.com/sue445/gitlabci-bundle-update-mr/) to check for gem updates. Recently, however, an update was made to a gem whose `homepage_uri` listed in the gemspec could not be resolved, causing an error when compare_linker attempted to retrieve the differences.
(Here is a real example: https://github.com/davetron5000/gli/pull/338)
I am unsure whether this gem should handle such cases, but I would appreciate it if you could consider a possible revision.
Thank you for reading this.

Use rubygems.org if `homepage_uri` cannot be resolved

---

.github/workflows/test.yml

See https://github.com/reviewdog/action-actionlint

Fix the warning of reviewdog/action-actionlint

---

compare_linker.gemspec

* resolves https://github.com/masutaka/compare_linker/issues/69
It reverts commit 674069d7c9c1a5b677a938d0e940dcaf624fa188.

Remove workaround for httpclient gem
